language: java
jdk:
  - oraclejdk7
  - openjdk6
  - openjdk7
env:
  global:
    - AWS_DEFAULT_REGION=us-west-1
    - secure: "IfUxje1QpdmYU2jdjg0lnrrOu2RzOKNGK0m1MLPxngaOLfW169h16ODZuh0pUIokAjpzvcMWHPMosIu1u8mvjoq92YRTtlqgLqckKxUQSVkQT2zyQv2Sbw6539rBDO0gvzknXz+SaVlEydE9Tb3UEPU3wRQtuFfjfaV+eucHR0E="
    - secure: "Omdfs8vsukqFWj6q0J17lJshVxQM4vQVXg5c3Z9VtfQtKPFdvt3Tek3hKqGSNfMPoUraV0Tu5QqFkqdHweQ2AYSe5Dyww9jjRNs2dLGb6on8k8YXm2YnDvGp1ZQ8miwvUEc+MD+uPfnGJvg6v1QqAhHZQNDwvWs6We6K9QP4Ht4="
  matrix:
    - EXTERNAL_AGENT_TEST=true EC2_TEST=true LIBVIRT_TEST=true DOCKER_TEST=true
    - CATTLE_DB_CATTLE_DATABASE=mysql
    - CATTLE_DB_CATTLE_DATABASE=h2
    - CATTLE_DB_CATTLE_DATABASE=hsqldb
    - CATTLE_DB_CATTLE_DATABASE=postgres MAVEN_ARGS=-Dpostgres
matrix:
  exclude:
    - jdk: openjdk6
      env: EXTERNAL_AGENT_TEST=true EC2_TEST=true LIBVIRT_TEST=true DOCKER_TEST=true
    - jdk: openjdk6
      env: CATTLE_DB_CATTLE_DATABASE=postgres MAVEN_ARGS=-Dpostgres
    - jdk: openjdk7
      env: EXTERNAL_AGENT_TEST=true EC2_TEST=true LIBVIRT_TEST=true DOCKER_TEST=true
services:
  - redis
before_install: ./tools/build/before.sh
install:
  - sudo apt-get update
  - sudo pip install tox
  - ./tools/build/build.sh
script: ./tools/build/runtests.sh
