/**
 * This class is generated by jOOQ
 */
package io.cattle.platform.core.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InstanceNetworkMapTable extends org.jooq.impl.TableImpl<io.cattle.platform.core.model.tables.records.InstanceNetworkMapRecord> {

	private static final long serialVersionUID = 649507608;

	/**
	 * The singleton instance of <code>cattle.instance_network_map</code>
	 */
	public static final io.cattle.platform.core.model.tables.InstanceNetworkMapTable INSTANCE_NETWORK_MAP = new io.cattle.platform.core.model.tables.InstanceNetworkMapTable();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<io.cattle.platform.core.model.tables.records.InstanceNetworkMapRecord> getRecordType() {
		return io.cattle.platform.core.model.tables.records.InstanceNetworkMapRecord.class;
	}

	/**
	 * The column <code>cattle.instance_network_map.id</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.InstanceNetworkMapRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>cattle.instance_network_map.name</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.InstanceNetworkMapRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>cattle.instance_network_map.kind</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.InstanceNetworkMapRecord, java.lang.String> KIND = createField("kind", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>cattle.instance_network_map.uuid</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.InstanceNetworkMapRecord, java.lang.String> UUID = createField("uuid", org.jooq.impl.SQLDataType.VARCHAR.length(128).nullable(false), this, "");

	/**
	 * The column <code>cattle.instance_network_map.description</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.InstanceNetworkMapRecord, java.lang.String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR.length(1024), this, "");

	/**
	 * The column <code>cattle.instance_network_map.state</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.InstanceNetworkMapRecord, java.lang.String> STATE = createField("state", org.jooq.impl.SQLDataType.VARCHAR.length(128).nullable(false), this, "");

	/**
	 * The column <code>cattle.instance_network_map.created</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.InstanceNetworkMapRecord, java.util.Date> CREATED = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP.asConvertedDataType(new io.cattle.platform.db.jooq.converter.DateConverter()), this, "");

	/**
	 * The column <code>cattle.instance_network_map.removed</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.InstanceNetworkMapRecord, java.util.Date> REMOVED = createField("removed", org.jooq.impl.SQLDataType.TIMESTAMP.asConvertedDataType(new io.cattle.platform.db.jooq.converter.DateConverter()), this, "");

	/**
	 * The column <code>cattle.instance_network_map.remove_time</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.InstanceNetworkMapRecord, java.util.Date> REMOVE_TIME = createField("remove_time", org.jooq.impl.SQLDataType.TIMESTAMP.asConvertedDataType(new io.cattle.platform.db.jooq.converter.DateConverter()), this, "");

	/**
	 * The column <code>cattle.instance_network_map.data</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.InstanceNetworkMapRecord, java.util.Map<String,Object>> DATA = createField("data", org.jooq.impl.SQLDataType.CLOB.length(65535).asConvertedDataType(new io.cattle.platform.db.jooq.converter.DataConverter()), this, "");

	/**
	 * The column <code>cattle.instance_network_map.instance_id</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.InstanceNetworkMapRecord, java.lang.Long> INSTANCE_ID = createField("instance_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>cattle.instance_network_map.network_id</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.InstanceNetworkMapRecord, java.lang.Long> NETWORK_ID = createField("network_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * Create a <code>cattle.instance_network_map</code> table reference
	 */
	public InstanceNetworkMapTable() {
		this("instance_network_map", null);
	}

	/**
	 * Create an aliased <code>cattle.instance_network_map</code> table reference
	 */
	public InstanceNetworkMapTable(java.lang.String alias) {
		this(alias, io.cattle.platform.core.model.tables.InstanceNetworkMapTable.INSTANCE_NETWORK_MAP);
	}

	private InstanceNetworkMapTable(java.lang.String alias, org.jooq.Table<io.cattle.platform.core.model.tables.records.InstanceNetworkMapRecord> aliased) {
		this(alias, aliased, null);
	}

	private InstanceNetworkMapTable(java.lang.String alias, org.jooq.Table<io.cattle.platform.core.model.tables.records.InstanceNetworkMapRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, io.cattle.platform.core.model.CattleTable.CATTLE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<io.cattle.platform.core.model.tables.records.InstanceNetworkMapRecord, java.lang.Long> getIdentity() {
		return io.cattle.platform.core.model.Keys.IDENTITY_INSTANCE_NETWORK_MAP;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<io.cattle.platform.core.model.tables.records.InstanceNetworkMapRecord> getPrimaryKey() {
		return io.cattle.platform.core.model.Keys.KEY_INSTANCE_NETWORK_MAP_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<io.cattle.platform.core.model.tables.records.InstanceNetworkMapRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<io.cattle.platform.core.model.tables.records.InstanceNetworkMapRecord>>asList(io.cattle.platform.core.model.Keys.KEY_INSTANCE_NETWORK_MAP_PRIMARY, io.cattle.platform.core.model.Keys.KEY_INSTANCE_NETWORK_MAP_IDX_INSTANCE_NETWORK_MAP_UUID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<io.cattle.platform.core.model.tables.records.InstanceNetworkMapRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<io.cattle.platform.core.model.tables.records.InstanceNetworkMapRecord, ?>>asList(io.cattle.platform.core.model.Keys.FK_INSTANCE_NETWORK_MAP__INSTANCE_ID, io.cattle.platform.core.model.Keys.FK_INSTANCE_NETWORK_MAP__NETWORK_ID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public io.cattle.platform.core.model.tables.InstanceNetworkMapTable as(java.lang.String alias) {
		return new io.cattle.platform.core.model.tables.InstanceNetworkMapTable(alias, this);
	}

	/**
	 * Rename this table
	 */
	public io.cattle.platform.core.model.tables.InstanceNetworkMapTable rename(java.lang.String name) {
		return new io.cattle.platform.core.model.tables.InstanceNetworkMapTable(name, null);
	}
}
