#!/bin/bash
set -e

apt-get update
apt-get install -y --no-install-recommends openjdk-7-jdk maven python-pip

pip install --upgrade pip tox

mkdir -p /usr/src/cattle
cd /usr/src/cattle
git clone https://github.com/cattleio/cattle.git .

mvn -DskipTests=true install || true
mvn dependency:go-offline || true
